#+title: Emacs Configuration
#+author: Tommaso Rossi

Emacs configuration with generic UI enhancements,  completion frameworks, syntax checkers and EXWM support.

Sources:

https://github.com/purcell/emacs.d

https://github.com/daviwil/dotfiles/blob/master/Emacs.org

https://github.com/daviwil/emacs-from-scratch

https://github.com/munen/emacs.d

Work in progress.

** Requirements

- JetBrainsMono font (package =ttf-jetbrains-mono= on Arch and Debian based distros)
- TDlib (only if =telega= command is used):
#+begin_src bash
git clone --depth 1 https://github.com/tdlib/td.git && cd td
mkdir build && cd build && cmake ../
make -j<n_cores>
sudo make install
#+end_src
- A TypeScript language server is TypeScript mode is enabled (see lsp-mode docs for details)
- virtualenv is Python mode is enabled (see elpy docs for details). Jedi should be installed as well, check =M-x elpy-config RET=.

** Getting started

#+begin_src bash
git clone --depth 1 https://github.com/tomrss/conf-emacs.git ~/.emacs.d
#+end_src

** EXWM

EXWM is configured in file =~/.emacs.d/desktop.el=, which has to be loaded separately, for example from the =.xinitrc= script:
#+begin_src bash
#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# (optional) set keyboard layout (e.g. setxkbmap it for italian)
setxkbmap <kbd_layout>

# (optional) set window compositor background image
picom --fade-delta=3 &
feh --bg-scale /path/to/background/image.jpg

# (optional) screen lock
xss-lock -- slock &

# launch emacs
exec dbus-launch --exit-with-session emacs -mm --debug-init -l ~/.emacs.d/desktop.el
#+end_src

When using a login manager, add a desktop entry for EXWM. If not, simply add following code to =.bash_profile= to start X server after login in TTY:
#+begin_src bash
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec startx
fi
#+end_src
