theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "custom"
command = "echo `uname` `uname -r` `uname -o`"
interval = "once"

# [[block]]
# block = "net"
# device = "wlp1s0"
# format = "{signal_strength} {speed_down}"
# interval = 5
# use_bits = false

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
device_format = "{icon}{name} {ap}"
ap_format = "{ssid^10} {strength}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
# format = "{available}{unit}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "custom"
command = ''' sensors | grep "Package id 0" | awk -F "  " '{ print $2 }' '''
interval = 5

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
