theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "net"
device = "wlan0"
format = "{signal_strength} {speed_down}"
interval = 5
# use_bits = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
# format = "{available}{unit}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
